LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := gameapi
LOCAL_SRC_FILES := $(LOCAL_PATH)/GameAPI/C/GameAPI/Game.c
LOCAL_C_INCLUDES := $(LOCAL_PATH)/GameAPI/C/GameAPI
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/GameAPI/C
LOCAL_CFLAGS := -std=c11 -DANDROID
include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := DropdashForAll
LOCAL_SRC_FILES := $(LOCAL_PATH)/dllmain.c
LOCAL_C_INCLUDES := $(LOCAL_PATH) \
	$(LOCAL_PATH)/GameAPI/C
LOCAL_STATIC_LIBRARIES := gameapi
LOCAL_CFLAGS := -std=c11 -DANDROID
LOCAL_LDLIBS := -llog
include $(BUILD_SHARED_LIBRARY)

LOCAL_PATH := $(call my-dir)
